export const data = [
  {
    source: "Broker",
    name: "legal-blouse.info",
    throughputValue: 7147,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "well-informed-inventor.name",
    throughputValue: 3745,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "frank-collision.name",
    throughputValue: 34978,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "constant-belly.name",
    throughputValue: 24155,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "calm-acid.biz",
    throughputValue: 49120,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "cumbersome-behold.info",
    throughputValue: 40083,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "hoarse-sailor.biz",
    throughputValue: 11041,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "spiffy-hippopotamus.net",
    throughputValue: 45130,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "third-hospitalisation.info",
    throughputValue: 48610,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "dreary-developing.org",
    throughputValue: 16067,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "shocked-integral.biz",
    throughputValue: 19362,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "round-school.info",
    throughputValue: 33113,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "old-statute.info",
    throughputValue: 5731,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "sore-tactics.name",
    throughputValue: 13114,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "evergreen-wholesaler.biz",
    throughputValue: 16275,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "lumpy-meringue.info",
    throughputValue: 30049,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "lone-perfection.org",
    throughputValue: 48637,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "pleasing-piece.com",
    throughputValue: 5663,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "finished-critic.biz",
    throughputValue: 7175,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "amused-sherry.info",
    throughputValue: 32916,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "heavenly-junket.biz",
    throughputValue: 28431,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "ripe-ankle.net",
    throughputValue: 8147,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "gifted-chamber.info",
    throughputValue: 34712,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "pastel-appliance.net",
    throughputValue: 1645,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "outstanding-hornet.info",
    throughputValue: 17893,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "supportive-workplace.name",
    throughputValue: 45705,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "lustrous-laptop.org",
    throughputValue: 16970,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "average-heartbeat.com",
    throughputValue: 27576,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "bleak-ratio.net",
    throughputValue: 34764,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "easy-blowhole.info",
    throughputValue: 31376,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "mild-octavo.biz",
    throughputValue: 47617,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "acceptable-porcelain.biz",
    throughputValue: 11844,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "feisty-taco.net",
    throughputValue: 28699,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "these-misplacement.biz",
    throughputValue: 34493,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "tall-surprise.name",
    throughputValue: 41268,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "scary-port.com",
    throughputValue: 25893,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "stupendous-ozone.org",
    throughputValue: 40670,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "monthly-dashboard.info",
    throughputValue: 47342,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "imperturbable-paramecium.biz",
    throughputValue: 40742,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "rewarding-spaghetti.net",
    throughputValue: 41955,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "tempting-humanity.name",
    throughputValue: 4799,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "unknown-trowel.biz",
    throughputValue: 35257,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "boiling-dough.name",
    throughputValue: 48834,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "weekly-eyelashes.biz",
    throughputValue: 48563,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "shameful-valuable.com",
    throughputValue: 4157,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "blind-astrolabe.info",
    throughputValue: 20644,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "babyish-solitaire.biz",
    throughputValue: 48919,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "primary-mention.com",
    throughputValue: 27593,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "oblong-metallurgist.name",
    throughputValue: 4321,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "ill-fated-infarction.org",
    throughputValue: 23041,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "outstanding-envelope.net",
    throughputValue: 12726,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "portly-salon.biz",
    throughputValue: 39027,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "shady-adapter.net",
    throughputValue: 31659,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "awesome-breakfast.net",
    throughputValue: 33661,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "unfortunate-tongue.net",
    throughputValue: 47819,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "bad-rubber.biz",
    throughputValue: 43313,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "gruesome-constitution.org",
    throughputValue: 11240,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "lumbering-calf.org",
    throughputValue: 26066,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "shallow-leading.com",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "motionless-romaine.info",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "buttery-manner.biz",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "pessimistic-clause.com",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "frightening-doubter.biz",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "silent-grandchild.name",
    throughputValue: 28885,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "woozy-snug.biz",
    throughputValue: 25474,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "quiet-horn.name",
    throughputValue: 48081,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "zealous-ladle.com",
    throughputValue: 36368,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "awesome-berry.com",
    throughputValue: 29219,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "short-term-lion.biz",
    throughputValue: 7909,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "grumpy-legacy.com",
    throughputValue: 26982,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "sweet-stepson.name",
    throughputValue: 12828,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "hungry-priority.name",
    throughputValue: 31495,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "piercing-anterior.name",
    throughputValue: 41872,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "aching-baseline.info",
    throughputValue: 6290,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "both-curtain.net",
    throughputValue: 389,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "ajar-green.org",
    throughputValue: 11144,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "exemplary-length.biz",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "warm-nursery.name",
    throughputValue: 10997,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "sunny-mukluk.com",
    throughputValue: 45758,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "open-numeric.org",
    throughputValue: 11368,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "proper-package.net",
    throughputValue: 4473,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "candid-riding.name",
    throughputValue: 19074,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "massive-conception.org",
    throughputValue: 43364,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "corny-solicitation.biz",
    throughputValue: 44124,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "grouchy-astrology.org",
    throughputValue: 12255,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "shadowy-otter.net",
    throughputValue: 39780,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "quick-witted-revenant.name",
    throughputValue: 44615,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "worthwhile-embassy.name",
    throughputValue: 8511,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "ordinary-graft.org",
    throughputValue: 24373,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "dimpled-nickname.name",
    throughputValue: 1396,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "fresh-nonbeliever.biz",
    throughputValue: 37772,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "ill-fated-cake.biz",
    throughputValue: 15233,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "tinted-highlight.org",
    throughputValue: 16481,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "darling-strength.net",
    throughputValue: 31514,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "spotless-pigpen.net",
    throughputValue: 14480,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "worst-kick-off.com",
    throughputValue: 40371,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "Broker",
    name: "golden-uncertainty.name",
    throughputValue: 48458,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "numb-decadence.net",
    throughputValue: 6913,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "zealous-euphonium.net",
    throughputValue: 21505,
    sendOnly: false,
    doNotInclude: false,
  },
  {
    source: "ServiceControl",
    name: "winged-nursery.org",
    throughputValue: 0,
    sendOnly: false,
    doNotInclude: false,
  },
];

export const setupData = [
  {
    description: "The grace period that faulted messages are kept before they are deleted.",
    name: "ServiceControl/SqlServer/ConnectionString",
  },
  {
    description: "The grace period that faulted messages are kept before they are deleted.",
    name: "ServiceControl/SqlServer/ConnectionString",
  },
  {
    description: "The grace period that faulted messages are kept before they are deleted.",
    name: "ServiceControl/SqlServer/ConnectionString",
  },
  {
    description: "The grace period that faulted messages are kept before they are deleted.",
    name: "ServiceControl/SqlServer/ConnectionString",
  },
  {
    description: "The grace period that faulted messages are kept before they are deleted.",
    name: "ServiceControl/SqlServer/ConnectionString",
  },
];
