// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceControl.Persistence.EFCore.PostgreSql;

#nullable disable

namespace ServiceControl.Persistence.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSqlServiceControlDbContext))]
    [Migration("20260722061312_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_message_id");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("body_content_type");

                    b.Property<int>("BodySize")
                        .HasColumnType("integer")
                        .HasColumnName("body_size");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("boolean")
                        .HasColumnName("body_stored_externally");

                    b.Property<string>("BodyText")
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text")
                        .HasColumnName("exception_message");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text")
                        .HasColumnName("exception_type");

                    b.Property<DateTime>("FirstTimeOfFailure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_time_of_failure");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_message");

                    b.Property<DateTime>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<DateTime>("LastTimeOfFailure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_time_of_failure");

                    b.Property<string>("MessageId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("NumberOfProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_processing_attempts");

                    b.Property<string>("QueueAddress")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("queue_address");

                    b.Property<string>("ReceivingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("receiving_endpoint_host");

                    b.Property<Guid?>("ReceivingEndpointHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_endpoint_host_id");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("receiving_endpoint_name");

                    b.Property<string>("SendingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sending_endpoint_host");

                    b.Property<Guid?>("SendingEndpointHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("sending_endpoint_host_id");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sending_endpoint_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_sent");

                    b.HasKey("UniqueMessageId")
                        .HasName("pk_failed_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_failed_messages_conversation_id");

                    b.HasIndex("QueueAddress")
                        .HasDatabaseName("ix_failed_messages_queue_address");

                    b.HasIndex("ReceivingEndpointName")
                        .HasDatabaseName("ix_failed_messages_receiving_endpoint_name");

                    b.HasIndex("StatusChangedAt")
                        .HasDatabaseName("ix_failed_messages_status_changed_at")
                        .HasFilter("status IN (2, 4)");

                    b.HasIndex("TimeSent")
                        .HasDatabaseName("ix_failed_messages_time_sent");

                    b.HasIndex("Status", "LastModified")
                        .HasDatabaseName("ix_failed_messages_status_last_modified");

                    b.ToTable("failed_messages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.Property<Guid>("FailedMessageUniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("failed_message_unique_id");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("group_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("FailedMessageUniqueId", "GroupId")
                        .HasName("pk_failed_message_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_failed_message_groups_group_id");

                    b.ToTable("failed_message_groups", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_message_id");

                    b.Property<string>("RetryId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("retry_id");

                    b.HasKey("UniqueMessageId")
                        .HasName("pk_failed_message_retries");

                    b.ToTable("failed_message_retries", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_known_endpoints");

                    b.ToTable("known_endpoints", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.HasOne("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("FailedMessageUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_failed_message_groups_failed_messages_failed_message_unique");
                });
#pragma warning restore 612, 618
        }
    }
}
