// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceControl.Persistence.EFCore.PostgreSql;

#nullable disable

namespace ServiceControl.Persistence.EFCore.PostgreSql.Migrations
{
    [DbContext(typeof(PostgreSqlServiceControlDbContext))]
    partial class PostgreSqlServiceControlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.CustomCheckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("category");

                    b.Property<string>("CustomCheckId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("custom_check_id");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("OriginatingEndpointHost")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originating_endpoint_host");

                    b.Property<Guid>("OriginatingEndpointHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("originating_endpoint_host_id");

                    b.Property<string>("OriginatingEndpointName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("originating_endpoint_name");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_custom_checks");

                    b.HasIndex("ReportedAt")
                        .HasDatabaseName("ix_custom_checks_reported_at");

                    b.HasIndex("Status", "ReportedAt")
                        .HasDatabaseName("ix_custom_checks_status_reported_at");

                    b.ToTable("custom_checks", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.EndpointSettingsEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("name");

                    b.Property<bool>("TrackInstances")
                        .HasColumnType("boolean")
                        .HasColumnName("track_instances");

                    b.HasKey("Name")
                        .HasName("pk_endpoint_settings");

                    b.ToTable("endpoint_settings", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.EventLogItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.PrimitiveCollection<List<string>>("RelatedTo")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("related_to");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("pk_event_log_items");

                    b.HasIndex("RaisedAt", "Id")
                        .IsDescending()
                        .HasDatabaseName("ix_event_log_items_raised_at_id");

                    b.ToTable("EventLogItems", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedErrorImportEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_message_id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("boolean")
                        .HasColumnName("body_stored_externally");

                    b.Property<string>("ExceptionInfo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("exception_info");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("failed_at");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("message_id");

                    b.HasKey("UniqueMessageId")
                        .HasName("pk_failed_error_imports");

                    b.HasIndex("FailedAt")
                        .HasDatabaseName("ix_failed_error_imports_failed_at");

                    b.ToTable("failed_error_imports", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_message_id");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("body_content_type");

                    b.Property<int>("BodySize")
                        .HasColumnType("integer")
                        .HasColumnName("body_size");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("boolean")
                        .HasColumnName("body_stored_externally");

                    b.Property<string>("BodyText")
                        .HasColumnType("text")
                        .HasColumnName("body_text");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("conversation_id");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text")
                        .HasColumnName("exception_message");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("text")
                        .HasColumnName("exception_type");

                    b.Property<string>("FailingEndpointAddress")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("failing_endpoint_address");

                    b.Property<DateTime>("FirstTimeOfFailure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_time_of_failure");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_message");

                    b.Property<DateTime>("LastAttemptedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_attempted_at");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<DateTime>("LastTimeOfFailure")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_time_of_failure");

                    b.Property<string>("MessageId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .HasColumnType("text")
                        .HasColumnName("message_type");

                    b.Property<int>("NumberOfProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_processing_attempts");

                    b.Property<string>("QueueAddress")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("queue_address");

                    b.Property<string>("ReceivingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("receiving_endpoint_host");

                    b.Property<Guid?>("ReceivingEndpointHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("receiving_endpoint_host_id");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("receiving_endpoint_name");

                    b.Property<string>("SendingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sending_endpoint_host");

                    b.Property<Guid?>("SendingEndpointHostId")
                        .HasColumnType("uuid")
                        .HasColumnName("sending_endpoint_host_id");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("sending_endpoint_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_sent");

                    b.HasKey("UniqueMessageId")
                        .HasName("pk_failed_messages");

                    b.HasIndex("ConversationId")
                        .HasDatabaseName("ix_failed_messages_conversation_id");

                    b.HasIndex("FailingEndpointAddress")
                        .HasDatabaseName("ix_failed_messages_failing_endpoint_address");

                    b.HasIndex("QueueAddress")
                        .HasDatabaseName("ix_failed_messages_queue_address");

                    b.HasIndex("ReceivingEndpointName")
                        .HasDatabaseName("ix_failed_messages_receiving_endpoint_name");

                    b.HasIndex("StatusChangedAt")
                        .HasDatabaseName("ix_failed_messages_status_changed_at")
                        .HasFilter("status IN (2, 4)");

                    b.HasIndex("TimeSent")
                        .HasDatabaseName("ix_failed_messages_time_sent");

                    b.HasIndex("Status", "LastModified")
                        .HasDatabaseName("ix_failed_messages_status_last_modified");

                    b.ToTable("failed_messages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.Property<Guid>("FailedMessageUniqueId")
                        .HasColumnType("uuid")
                        .HasColumnName("failed_message_unique_id");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("group_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("type");

                    b.HasKey("FailedMessageUniqueId", "GroupId")
                        .HasName("pk_failed_message_groups");

                    b.HasIndex("GroupId")
                        .HasDatabaseName("ix_failed_message_groups_group_id");

                    b.ToTable("failed_message_groups", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uuid")
                        .HasColumnName("unique_message_id");

                    b.Property<string>("RetryId")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("retry_id");

                    b.HasKey("UniqueMessageId")
                        .HasName("pk_failed_message_retries");

                    b.ToTable("failed_message_retries", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("host");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_known_endpoints");

                    b.ToTable("known_endpoints", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.SubscriptionEntity", b =>
                {
                    b.Property<string>("MessageType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_type");

                    b.Property<string>("TransportAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transport_address");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("endpoint");

                    b.HasKey("MessageType", "TransportAddress")
                        .HasName("pk_subscriptions");

                    b.ToTable("subscriptions", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.TrialMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("TrialEndDate")
                        .HasColumnType("date")
                        .HasColumnName("trial_end_date");

                    b.HasKey("Id")
                        .HasName("pk_trial_metadata");

                    b.ToTable("trial_metadata", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        });
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.HasOne("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("FailedMessageUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_failed_message_groups_failed_messages_failed_message_unique");
                });
#pragma warning restore 612, 618
        }
    }
}
