// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceControl.Audit.Persistence.EFCore.SqlServer;

#nullable disable

namespace ServiceControl.Audit.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerAuditDbContext))]
    [Migration("20260928032751_AddFullTextSearch")]
    partial class AddFullTextSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Audit.Persistence.EFCore.Entities.AuditMessageEntity", b =>
                {
                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("BodyContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<int>("BodyState")
                        .HasColumnType("int");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long?>("CriticalTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeliveryTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProcessingTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceivingEndpointHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ReceivingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SendingEndpointHost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("SendingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SendingEndpointName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("CreatedOn", "Id");

                    b.HasIndex("ConversationId");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("TimeSent");

                    b.HasIndex("UniqueMessageId");

                    b.HasIndex("ReceivingEndpointName", "CreatedOn");

                    b.ToTable("AuditMessages");
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.EFCore.Entities.FailedAuditImportEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UniqueMessageId");

                    b.HasIndex("FailedAt", "UniqueMessageId");

                    b.ToTable("FailedAuditImports");
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.EFCore.Entities.SagaSnapshotEntity", b =>
                {
                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatingMessageJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingMessagesJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SagaType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateAfterChange")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("CreatedOn", "Id");

                    b.HasIndex("SagaId", "FinishTime");

                    b.ToTable("SagaSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
