FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /servicecontrol.monitoring

ADD /ServiceControl.Transports.SQS/bin/Release/net462 .
ADD /ServiceControl.Monitoring/bin/Release/net462 .

ENV "Monitoring/TransportType"="ServiceControl.Transports.SQS.SQSTransportCustomization, ServiceControl.Transports.SQS"
ENV "Monitoring/HttpHostName"="*"

EXPOSE 33633

ENTRYPOINT ["ServiceControl.Monitoring.exe", "--portable"]