FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /servicecontrol.monitoring

ADD /ServiceControl.Transports.RabbitMQ/bin/Release/net462 .
ADD /ServiceControl.Monitoring/bin/Release/net462 .

ENV "Monitoring/TransportType"="ServiceControl.Transports.ASQ.ASQTransportCustomization, ServiceControl.Transports.ASQ"
ENV "Monitoring/Hostname"="*"

ENTRYPOINT ["ServiceControl.Monitoring.exe", "--portable", "--setup"]