using System.Runtime.CompilerServices;

[assembly: InternalsVisibleTo("ServiceControl.Audit.UnitTests")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.AcceptanceTests")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.AcceptanceTests.RavenDB")]
[assembly: InternalsVisibleTo("ServiceControl.MultiInstance.AcceptanceTests")]
[assembly: InternalsVisibleTo("ServiceControl.Loadtests.Reporter")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.RavenDb")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.RavenDb5")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.SqlServer")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.InMemory")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.Tests")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.Tests.RavenDB")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.Tests.RavenDb5")]
[assembly: InternalsVisibleTo("ServiceControl.Audit.Persistence.Tests.SqlServer")]
