services:

  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sc
      POSTGRES_PASSWORD: ServiceControl1!
    command: --max-prepared-transactions=105

  # Add service health dependencies to ServiceControl instances
  servicecontrol:
    depends_on:
      postgres:
        condition: service_healthy
  servicecontrol-audit:
    depends_on:
      postgres:
        condition: service_healthy
  servicecontrol-monitoring:
    depends_on:
      postgres:
        condition: service_healthy