name: service-platform

services:
  servicecontrol:
    image: ghcr.io/particular/servicecontrol:${SERVICECONTROL_TAG}
    env_file: .env
    ports:
      - "33333:33333"
    environment:
      RAVENDB_CONNECTIONSTRING: http://servicecontrol-db:8080
      REMOTEINSTANCES: '[{"api_uri":"http://servicecontrol-audit:44444/api"}]'
    command: --setup-and-run
    depends_on:
      servicecontrol-db:
        condition: service_healthy

  # WARNING: A single database container should not be shared between multiple ServiceControl instances in production scenarios.
  servicecontrol-db:
    image: ghcr.io/particular/servicecontrol-ravendb:${SERVICECONTROL_TAG}
    ports:
      - "8080:8080"
    volumes:
      - db-config:/etc/ravendb
      - db-data:/var/lib/ravendb/data

  servicecontrol-audit:
    image: ghcr.io/particular/servicecontrol-audit:${SERVICECONTROL_TAG}
    env_file: .env
    ports:
      - "44444:44444"
    environment:
      RAVENDB_CONNECTIONSTRING: http://servicecontrol-db:8080
    command: --setup-and-run
    depends_on:
      servicecontrol-db:
        condition: service_healthy

  servicecontrol-monitoring:
    image: ghcr.io/particular/servicecontrol-monitoring:${SERVICECONTROL_TAG}
    env_file: .env
    command: --setup-and-run
    ports:
      - "33633:33633"

volumes:
  db-config:
  db-data:
