using System.Collections.Concurrent;
using System.Diagnostics;
using System.Diagnostics.Metrics;
using Microsoft.Extensions.Logging;
using NServiceBus;
using TestingTool.Contracts;
using TestingTool.Scenarios;

namespace TestingTool;

/// <summary>
/// Manages the lifecycle of all scenarios: start, stop, rate control, auto-stop on duration,
/// and per-scenario error counting. Load is generated by sending <see cref="LoadMessage"/> to the
/// NServiceBus endpoint at a controlled rate; the <see cref="FailingMessageHandler"/> throws based
/// on the scenario's failure logic, routing failures to the ServiceControl error queue.
/// </summary>
public sealed class ScenarioRunner
{
    private readonly IMessageSession _session;
    private readonly IScenarioRegistry _registry;
    private readonly TestingToolMetrics _metrics;
    private readonly Meter _meter;
    private readonly ILogger<ScenarioRunner> _logger;

    // Per-scenario runtime state.
    private readonly ConcurrentDictionary<string, ScenarioRuntime> _running = new(StringComparer.OrdinalIgnoreCase);

    public ScenarioRunner(IMessageSession session, IScenarioRegistry registry, TestingToolMetrics metrics, Meter meter, ILogger<ScenarioRunner> logger)
    {
        _session = session;
        _registry = registry;
        _metrics = metrics;
        _meter = meter;
        _logger = logger;
    }

    /// <summary>Starts a scenario with an optional rate override and auto-stop duration.</summary>
    public bool TryStart(string scenarioName, double? rate, TimeSpan? duration, out string? error)
    {
        var scenario = _registry.Get(scenarioName);
        if (scenario is null)
        {
            error = $"Unknown scenario '{scenarioName}'";
            return false;
        }

        if (_running.ContainsKey(scenarioName))
        {
            error = $"Scenario '{scenarioName}' is already running";
            return false;
        }

        var targetRate = rate ?? scenario.DefaultRate;
        if (targetRate <= 0)
        {
            error = "Rate must be greater than 0";
            return false;
        }

        var runtime = new ScenarioRuntime(scenario, targetRate, duration, _meter, _logger);
        if (_running.TryAdd(scenarioName, runtime))
        {
            runtime.Start(GenerateLoadAsync, OnLoopCompleted);
            UpdateAggregateMetrics();
            _logger.LogInformation("Started scenario {Scenario} at {Rate:F1} msg/s{Duration}",
                scenarioName, targetRate, duration is null ? "" : $" for {duration.Value}");
            error = null;
            return true;
        }

        error = $"Scenario '{scenarioName}' is already running";
        return false;
    }

    /// <summary>Stops a running scenario.</summary>
    public bool TryStop(string scenarioName)
    {
        if (_running.TryRemove(scenarioName, out var runtime))
        {
            runtime.Stop();
            UpdateAggregateMetrics();
            _logger.LogInformation("Stopped scenario {Scenario} after {Errors} errors",
                scenarioName, runtime.ErrorsSent);
            return true;
        }
        return false;
    }

    /// <summary>
    /// Called when a scenario's load loop exits on its own (duration elapsed or crash) so it
    /// stops reporting as running. Only removes this exact runtime, never a newer restart.
    /// </summary>
    private void OnLoopCompleted(ScenarioRuntime runtime)
    {
        if (_running.TryRemove(KeyValuePair.Create(runtime.Scenario.Name, runtime)))
        {
            runtime.Stop();
            UpdateAggregateMetrics();
            _logger.LogInformation("Scenario {Scenario} finished after {Sent} messages, {Errors} errors",
                runtime.Scenario.Name, runtime.MessagesSent, runtime.ErrorsSent);
        }
    }

    /// <summary>Stops all running scenarios (used on shutdown).</summary>
    public void StopAll()
    {
        foreach (var name in _running.Keys)
            TryStop(name);
    }

    public List<ScenarioInfo> GetSnapshot()
    {
        var list = new List<ScenarioInfo>();
        foreach (var scenario in _registry.All)
        {
            _running.TryGetValue(scenario.Name, out var runtime);
            list.Add(new ScenarioInfo
            {
                Name = scenario.Name,
                Description = scenario.Description,
                Category = scenario.Category,
                Running = runtime is not null,
                CurrentRate = runtime?.TargetRate ?? 0,
                AchievedRate = Math.Round(runtime?.AchievedRate ?? 0, 1),
                MessagesSent = runtime?.MessagesSent ?? 0,
                ErrorsSent = runtime?.ErrorsSent ?? 0,
                DefaultRate = scenario.DefaultRate,
                Cooldown = scenario.Cooldown?.ToString()
            });
        }
        return list;
    }

    private void UpdateAggregateMetrics()
    {
        _metrics.SetActiveScenarios(_running.Count);
        _metrics.SetCurrentRate(_running.Values.Sum(r => r.TargetRate));
    }

    // Timer tick bounds for the load loop. The floor keeps PeriodicTimer valid (it rejects
    // sub-millisecond periods) and avoids spinning; the ceiling keeps low-rate scenarios responsive.
    private static readonly TimeSpan MinTick = TimeSpan.FromMilliseconds(10);
    private static readonly TimeSpan MaxTick = TimeSpan.FromSeconds(1);

    /// <summary>
    /// The load generation loop: sends LoadMessages at the target rate until cancelled.
    /// Pacing is by elapsed time rather than one message per tick: each tick sends however many
    /// messages are owed (<c>floor(elapsed * rate) - sent</c>), so timer coarseness (~15.6 ms on
    /// Windows) and send latency are caught up on the next tick instead of lowering the rate.
    /// </summary>
    private async Task GenerateLoadAsync(ScenarioRuntime runtime, CancellationToken ct)
    {
        var tick = TimeSpan.FromSeconds(Math.Clamp(1.0 / runtime.TargetRate, MinTick.TotalSeconds, MaxTick.TotalSeconds));
        using var timer = new PeriodicTimer(tick);
        var clock = Stopwatch.StartNew();
        long sequence = 0;

        try
        {
            while (await timer.WaitForNextTickAsync(ct))
            {
                var due = (long)(clock.Elapsed.TotalSeconds * runtime.TargetRate);
                while (sequence < due && !ct.IsCancellationRequested)
                {
                    await SendOneAsync(runtime, ++sequence, ct);
                }
            }
        }
        catch (OperationCanceledException) { }
    }

    private async Task SendOneAsync(ScenarioRuntime runtime, long seq, CancellationToken ct)
    {
        var scenario = runtime.Scenario;

        // Plausible JSON body (~3–6 KB) seeded with searchable terms so ServiceControl's
        // full-text search index has real content to exercise.
        var textBody = MessageTextGenerator.GenerateBody(seq);

        // Deterministic message id shared with the handler: FailingMessageHandler calls
        // scenario.ShouldFail(context.MessageId), so setting the id here ensures the
        // failure decision counted below matches the decision the handler actually makes.
        var messageId = $"{scenario.Name}-{seq}-{runtime.StartedAt.Ticks}";

        var sendOptions = new SendOptions();
        sendOptions.RouteToThisEndpoint();
        sendOptions.SetMessageId(messageId);
        sendOptions.SetHeader("TestingTool.Scenario", scenario.Name);

        try
        {
            await _session.Send(new LoadMessage { Sequence = seq, TextBody = textBody }, sendOptions, ct);
            runtime.IncrementSent();

            // If the scenario fails for this message id (same decision as the handler),
            // count it as an error sent.
            if (scenario.ShouldFail(messageId))
            {
                runtime.IncrementErrors();
                _metrics.AddErrorsSent(1);
                runtime.ErrorsCounter.Add(1, new KeyValuePair<string, object?>("scenario", scenario.Name));
            }
        }
        catch (Exception ex)
        {
            _logger.LogDebug(ex, "Send failed for scenario {Scenario} seq {Seq}", scenario.Name, seq);
        }
    }
}

/// <summary>Per-scenario runtime state: rate, counters, cancellation, and auto-stop timer.</summary>
internal sealed class ScenarioRuntime
{
    private readonly Meter _meter;
    private readonly ILogger _logger;
    private readonly Counter<long> _errorsCounter;
    private long _errorsSent;
    private long _messagesSent;
    private CancellationTokenSource? _cts;
    private Task? _loop;

    public ScenarioRuntime(IScenario scenario, double rate, TimeSpan? duration, Meter meter, ILogger logger)
    {
        Scenario = scenario;
        TargetRate = rate;
        Duration = duration;
        StartedAt = DateTimeOffset.UtcNow;
        _meter = meter;
        _logger = logger;
        _errorsCounter = meter.CreateCounter<long>("errors_sent_total");
    }

    public IScenario Scenario { get; }
    public double TargetRate { get; }
    public TimeSpan? Duration { get; }
    public DateTimeOffset StartedAt { get; }
    public long ErrorsSent => Interlocked.Read(ref _errorsSent);
    public long MessagesSent => Interlocked.Read(ref _messagesSent);
    public Counter<long> ErrorsCounter => _errorsCounter;

    /// <summary>Messages actually sent per second since start, for comparison with <see cref="TargetRate"/>.</summary>
    public double AchievedRate
    {
        get
        {
            var elapsed = (DateTimeOffset.UtcNow - StartedAt).TotalSeconds;
            return elapsed > 0 ? MessagesSent / elapsed : 0;
        }
    }

    public long IncrementErrors() => Interlocked.Increment(ref _errorsSent);
    public long IncrementSent() => Interlocked.Increment(ref _messagesSent);

    /// <summary>
    /// Starts the load loop. <paramref name="completed"/> runs whenever the loop exits, whether
    /// from <see cref="Stop"/>, the duration elapsing, or a crash.
    /// </summary>
    public void Start(Func<ScenarioRuntime, CancellationToken, Task> generate, Action<ScenarioRuntime> completed)
    {
        _cts = Duration is { } d
            ? new CancellationTokenSource(d)
            : new CancellationTokenSource();

        // Captured so Stop() nulling/disposing _cts can't race the loop's startup. No token is
        // passed to Task.Run so the body (and the completion callback) always runs.
        var token = _cts.Token;
        _loop = Task.Run(async () =>
        {
            try
            {
                await generate(this, token);
            }
            catch (OperationCanceledException) { }
            catch (Exception ex)
            {
                _logger.LogError(ex, "Load generation loop for {Scenario} crashed", Scenario.Name);
            }
            finally
            {
                completed(this);
            }
        });
    }

    public void Stop()
    {
        _cts?.Cancel();
        _cts?.Dispose();
        _cts = null;
    }
}