version: '3'

services:

  rabbitmq:
    image: rabbitmq:3-management
    platform: linux
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq/mnesia
      - ./enabled_plugins:/etc/rabbitmq/enabled_plugins

volumes:
  rabbitmq-data:
