// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceControl.Persistence.Sql.MySQL;

#nullable disable

namespace ServiceControl.Persistence.Sql.MySQL.Migrations
{
    [DbContext(typeof(MySqlDbContext))]
    [Migration("20251214204322_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.ArchiveOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("int");

                    b.Property<int>("ArchiveType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrentBatch")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime?>("Last")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumberOfBatches")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMessagesArchived")
                        .HasColumnType("int");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TotalNumberOfMessages")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArchiveState");

                    b.HasIndex("RequestId");

                    b.HasIndex("ArchiveType", "RequestId")
                        .IsUnique();

                    b.ToTable("ArchiveOperations", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.CustomCheckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("CustomCheckId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("longtext");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("CustomChecks", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.EndpointSettingsEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool>("TrackInstances")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Name");

                    b.ToTable("EndpointSettings", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.EventLogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("EventType")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RelatedTo")
                        .HasMaxLength(4000)
                        .HasColumnType("varchar(4000)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAt");

                    b.ToTable("EventLogItems", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.ExternalIntegrationDispatchRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DispatchContextJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ExternalIntegrationDispatchRequests", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedErrorImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("longtext");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("FailedErrorImports", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<TimeSpan?>("CriticalTime")
                        .HasColumnType("time(6)");

                    b.Property<TimeSpan?>("DeliveryTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("longtext");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("FailureGroupsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("NumberOfProcessingAttempts")
                        .HasColumnType("int");

                    b.Property<string>("PrimaryFailureGroupId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProcessingAttemptsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("time(6)");

                    b.Property<string>("QueueAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UniqueMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("CriticalTime");

                    b.HasIndex("DeliveryTime");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessingTime");

                    b.HasIndex("UniqueMessageId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "LastProcessedAt");

                    b.HasIndex("MessageType", "TimeSent");

                    b.HasIndex("ReceivingEndpointName", "TimeSent");

                    b.HasIndex("Status", "LastProcessedAt");

                    b.HasIndex("Status", "QueueAddress");

                    b.HasIndex("PrimaryFailureGroupId", "Status", "LastProcessedAt");

                    b.HasIndex("QueueAddress", "Status", "LastProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "Status", "LastProcessedAt");

                    b.ToTable("FailedMessages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("FailedMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RetryBatchId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("StageAttempts")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FailedMessageId");

                    b.HasIndex("RetryBatchId");

                    b.ToTable("FailedMessageRetries", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.GroupCommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupComments", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("HostDisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("Monitored")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("Id");

                    b.ToTable("KnownEndpoints", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.MessageBodyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("longblob");

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("Etag")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("MessageBodies", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.MessageRedirectsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("RedirectsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("MessageRedirects", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.NotificationsSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("EmailSettingsJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("NotificationsSettings", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.QueueAddressEntity", b =>
                {
                    b.Property<string>("PhysicalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("FailedMessageCount")
                        .HasColumnType("int");

                    b.HasKey("PhysicalAddress");

                    b.ToTable("QueueAddresses", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Classifier")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Context")
                        .HasColumnType("longtext");

                    b.Property<string>("FailureRetriesJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("InitialBatchSize")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Last")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Originator")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("RetrySessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<int>("RetryType")
                        .HasColumnType("int");

                    b.Property<string>("StagingId")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RetrySessionId");

                    b.HasIndex("StagingId");

                    b.HasIndex("Status");

                    b.ToTable("RetryBatches", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryBatchNowForwardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("RetryBatchId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("RetryBatchId");

                    b.ToTable("RetryBatchNowForwarding", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("HistoricOperationsJson")
                        .HasColumnType("longtext");

                    b.Property<string>("UnacknowledgedOperationsJson")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("RetryHistory", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.SubscriptionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("MessageTypeTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("MessageTypeVersion")
                        .HasColumnType("int");

                    b.Property<string>("SubscribersJson")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("MessageTypeTypeName", "MessageTypeVersion")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.TrialLicenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<DateOnly>("TrialEndDate")
                        .HasColumnType("date");

                    b.HasKey("Id");

                    b.ToTable("TrialLicense", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
