// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceControl.Persistence.Sql.PostgreSQL;

#nullable disable

namespace ServiceControl.Persistence.Sql.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    [Migration("20251214204335_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.ArchiveOperationEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("ArchiveState")
                        .HasColumnType("integer")
                        .HasColumnName("archive_state");

                    b.Property<int>("ArchiveType")
                        .HasColumnType("integer")
                        .HasColumnName("archive_type");

                    b.Property<DateTime?>("CompletionTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completion_time");

                    b.Property<int>("CurrentBatch")
                        .HasColumnType("integer")
                        .HasColumnName("current_batch");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_name");

                    b.Property<DateTime?>("Last")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last");

                    b.Property<int>("NumberOfBatches")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_batches");

                    b.Property<int>("NumberOfMessagesArchived")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_messages_archived");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_id");

                    b.Property<DateTime>("Started")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started");

                    b.Property<int>("TotalNumberOfMessages")
                        .HasColumnType("integer")
                        .HasColumnName("total_number_of_messages");

                    b.HasKey("Id")
                        .HasName("p_k_archive_operations");

                    b.HasIndex("ArchiveState");

                    b.HasIndex("RequestId");

                    b.HasIndex("ArchiveType", "RequestId")
                        .IsUnique();

                    b.ToTable("ArchiveOperations", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.CustomCheckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("category");

                    b.Property<string>("CustomCheckId")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("custom_check_id");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_name");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text")
                        .HasColumnName("failure_reason");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("host");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reported_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_custom_checks");

                    b.HasIndex("Status");

                    b.ToTable("CustomChecks", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.EndpointSettingsEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("name");

                    b.Property<bool>("TrackInstances")
                        .HasColumnType("boolean")
                        .HasColumnName("track_instances");

                    b.HasKey("Name");

                    b.ToTable("EndpointSettings", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.EventLogItemEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("RelatedTo")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("related_to");

                    b.Property<int>("Severity")
                        .HasColumnType("integer")
                        .HasColumnName("severity");

                    b.HasKey("Id")
                        .HasName("p_k_event_log_items");

                    b.HasIndex("RaisedAt");

                    b.ToTable("EventLogItems", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.ExternalIntegrationDispatchRequestEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DispatchContextJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("dispatch_context_json");

                    b.HasKey("Id")
                        .HasName("p_k_external_integration_dispatch_requests");

                    b.HasIndex("CreatedAt");

                    b.ToTable("ExternalIntegrationDispatchRequests", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedErrorImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("text")
                        .HasColumnName("exception_info");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_json");

                    b.HasKey("Id")
                        .HasName("p_k_failed_error_imports");

                    b.ToTable("FailedErrorImports", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("conversation_id");

                    b.Property<TimeSpan?>("CriticalTime")
                        .HasColumnType("interval")
                        .HasColumnName("critical_time");

                    b.Property<TimeSpan?>("DeliveryTime")
                        .HasColumnType("interval")
                        .HasColumnName("delivery_time");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("text")
                        .HasColumnName("exception_message");

                    b.Property<string>("ExceptionType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("exception_type");

                    b.Property<string>("FailureGroupsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_groups_json");

                    b.Property<DateTime?>("LastProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_processed_at");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<int?>("NumberOfProcessingAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("number_of_processing_attempts");

                    b.Property<string>("PrimaryFailureGroupId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("primary_failure_group_id");

                    b.Property<string>("ProcessingAttemptsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("processing_attempts_json");

                    b.Property<TimeSpan?>("ProcessingTime")
                        .HasColumnType("interval")
                        .HasColumnName("processing_time");

                    b.Property<string>("QueueAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("queue_address");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("receiving_endpoint_name");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("sending_endpoint_name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_sent");

                    b.Property<string>("UniqueMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unique_message_id");

                    b.HasKey("Id")
                        .HasName("p_k_failed_messages");

                    b.HasIndex("CriticalTime");

                    b.HasIndex("DeliveryTime");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessingTime");

                    b.HasIndex("UniqueMessageId")
                        .IsUnique();

                    b.HasIndex("ConversationId", "LastProcessedAt");

                    b.HasIndex("MessageType", "TimeSent");

                    b.HasIndex("ReceivingEndpointName", "TimeSent");

                    b.HasIndex("Status", "LastProcessedAt");

                    b.HasIndex("Status", "QueueAddress");

                    b.HasIndex("PrimaryFailureGroupId", "Status", "LastProcessedAt");

                    b.HasIndex("QueueAddress", "Status", "LastProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "Status", "LastProcessedAt");

                    b.ToTable("FailedMessages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("FailedMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("failed_message_id");

                    b.Property<string>("RetryBatchId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("retry_batch_id");

                    b.Property<int>("StageAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("stage_attempts");

                    b.HasKey("Id")
                        .HasName("p_k_failed_message_retries");

                    b.HasIndex("FailedMessageId");

                    b.HasIndex("RetryBatchId");

                    b.ToTable("FailedMessageRetries", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.GroupCommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("comment");

                    b.Property<string>("GroupId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("group_id");

                    b.HasKey("Id")
                        .HasName("p_k_group_comments");

                    b.HasIndex("GroupId");

                    b.ToTable("GroupComments", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("endpoint_name");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("host");

                    b.Property<string>("HostDisplayName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("host_display_name");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<bool>("Monitored")
                        .HasColumnType("boolean")
                        .HasColumnName("monitored");

                    b.HasKey("Id")
                        .HasName("p_k_known_endpoints");

                    b.ToTable("KnownEndpoints", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.MessageBodyEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("body");

                    b.Property<int>("BodySize")
                        .HasColumnType("integer")
                        .HasColumnName("body_size");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<string>("Etag")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etag");

                    b.HasKey("Id")
                        .HasName("p_k_message_bodies");

                    b.ToTable("MessageBodies", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.MessageRedirectsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ETag")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("e_tag");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_modified");

                    b.Property<string>("RedirectsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("redirects_json");

                    b.HasKey("Id")
                        .HasName("p_k_message_redirects");

                    b.ToTable("MessageRedirects", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.NotificationsSettingsEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("EmailSettingsJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email_settings_json");

                    b.HasKey("Id")
                        .HasName("p_k_notifications_settings");

                    b.ToTable("NotificationsSettings", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.QueueAddressEntity", b =>
                {
                    b.Property<string>("PhysicalAddress")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("physical_address");

                    b.Property<int>("FailedMessageCount")
                        .HasColumnType("integer")
                        .HasColumnName("failed_message_count");

                    b.HasKey("PhysicalAddress");

                    b.ToTable("QueueAddresses", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Classifier")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("classifier");

                    b.Property<string>("Context")
                        .HasColumnType("text")
                        .HasColumnName("context");

                    b.Property<string>("FailureRetriesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("failure_retries_json");

                    b.Property<int>("InitialBatchSize")
                        .HasColumnType("integer")
                        .HasColumnName("initial_batch_size");

                    b.Property<DateTime?>("Last")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last");

                    b.Property<string>("Originator")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("originator");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("request_id");

                    b.Property<string>("RetrySessionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("retry_session_id");

                    b.Property<int>("RetryType")
                        .HasColumnType("integer")
                        .HasColumnName("retry_type");

                    b.Property<string>("StagingId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("staging_id");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("p_k_retry_batches");

                    b.HasIndex("RetrySessionId");

                    b.HasIndex("StagingId");

                    b.HasIndex("Status");

                    b.ToTable("RetryBatches", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryBatchNowForwardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("RetryBatchId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("retry_batch_id");

                    b.HasKey("Id")
                        .HasName("p_k_retry_batch_now_forwarding");

                    b.HasIndex("RetryBatchId");

                    b.ToTable("RetryBatchNowForwarding", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.RetryHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<string>("HistoricOperationsJson")
                        .HasColumnType("text")
                        .HasColumnName("historic_operations_json");

                    b.Property<string>("UnacknowledgedOperationsJson")
                        .HasColumnType("text")
                        .HasColumnName("unacknowledged_operations_json");

                    b.HasKey("Id")
                        .HasName("p_k_retry_history");

                    b.ToTable("RetryHistory", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.SubscriptionEntity", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("id");

                    b.Property<string>("MessageTypeTypeName")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type_type_name");

                    b.Property<int>("MessageTypeVersion")
                        .HasColumnType("integer")
                        .HasColumnName("message_type_version");

                    b.Property<string>("SubscribersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subscribers_json");

                    b.HasKey("Id")
                        .HasName("p_k_subscriptions");

                    b.HasIndex("MessageTypeTypeName", "MessageTypeVersion")
                        .IsUnique();

                    b.ToTable("Subscriptions", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.TrialLicenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly>("TrialEndDate")
                        .HasColumnType("date")
                        .HasColumnName("trial_end_date");

                    b.HasKey("Id")
                        .HasName("p_k_trial_licenses");

                    b.ToTable("TrialLicense", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
