// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using ServiceControl.Persistence.Sql.PostgreSQL;

#nullable disable

namespace ServiceControl.Persistence.Sql.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    partial class PostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.TrialLicenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id")
                        .HasDefaultValue(1);

                    b.Property<DateOnly>("TrialEndDate")
                        .HasColumnType("date")
                        .HasColumnName("trialenddate");

                    b.HasKey("Id");

                    b.ToTable("triallicense", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
