// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceControl.Persistence.Sql.PostgreSQL;

#nullable disable

namespace ServiceControl.Persistence.Sql.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlDbContext))]
    partial class PostgreSqlDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.DailyThroughputEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint_name");

                    b.Property<long>("MessageCount")
                        .HasColumnType("bigint")
                        .HasColumnName("message_count");

                    b.Property<string>("ThroughputSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("throughput_source");

                    b.HasKey("Id")
                        .HasName("p_k_throughput");

                    b.HasIndex(new[] { "EndpointName", "ThroughputSource", "Date" }, "UC_DailyThroughput_EndpointName_ThroughputSource_Date")
                        .IsUnique();

                    b.ToTable("DailyThroughput", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.LicensingMetadataEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("data");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("key");

                    b.HasKey("Id")
                        .HasName("p_k_licensing_metadata");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("LicensingMetadata", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.ThroughputEndpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("EndpointIndicators")
                        .HasColumnType("text")
                        .HasColumnName("endpoint_indicators");

                    b.Property<string>("EndpointName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("endpoint_name");

                    b.Property<DateOnly>("LastCollectedData")
                        .HasColumnType("date")
                        .HasColumnName("last_collected_data");

                    b.Property<string>("SanitizedEndpointName")
                        .HasColumnType("text")
                        .HasColumnName("sanitized_endpoint_name");

                    b.Property<string>("Scope")
                        .HasColumnType("text")
                        .HasColumnName("scope");

                    b.Property<string>("ThroughputSource")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("throughput_source");

                    b.Property<string>("UserIndicator")
                        .HasColumnType("text")
                        .HasColumnName("user_indicator");

                    b.HasKey("Id")
                        .HasName("p_k_endpoints");

                    b.HasIndex(new[] { "EndpointName", "ThroughputSource" }, "UC_ThroughputEndpoint_EndpointName_ThroughputSource")
                        .IsUnique();

                    b.ToTable("ThroughputEndpoint", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.Sql.Core.Entities.TrialLicenseEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasDefaultValue(1)
                        .HasColumnName("id");

                    b.Property<DateOnly>("TrialEndDate")
                        .HasColumnType("date")
                        .HasColumnName("trial_end_date");

                    b.HasKey("Id")
                        .HasName("p_k_trial_licenses");

                    b.ToTable("TrialLicense", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
