// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceControl.Persistence.EFCore.SqlServer;

#nullable disable

namespace ServiceControl.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerServiceControlDbContext))]
    [Migration("20260722061320_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("bit");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FirstTimeOfFailure")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTimeOfFailure")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProcessingAttempts")
                        .HasColumnType("int");

                    b.Property<string>("QueueAddress")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ReceivingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ReceivingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SendingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("SendingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueMessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("QueueAddress");

                    b.HasIndex("ReceivingEndpointName");

                    b.HasIndex("StatusChangedAt")
                        .HasFilter("[Status] IN (2, 4)");

                    b.HasIndex("TimeSent");

                    b.HasIndex("Status", "LastModified");

                    b.ToTable("FailedMessages");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.Property<Guid>("FailedMessageUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FailedMessageUniqueId", "GroupId");

                    b.HasIndex("GroupId");

                    b.ToTable("FailedMessageGroups");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RetryId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueMessageId");

                    b.ToTable("FailedMessageRetries");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Monitored")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("KnownEndpoints");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.HasOne("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("FailedMessageUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
