// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceControl.Persistence.EFCore.SqlServer;

#nullable disable

namespace ServiceControl.Persistence.EFCore.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerServiceControlDbContext))]
    [Migration("20260807053830_AddLicensingThroughput")]
    partial class AddLicensingThroughput
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.ArchiveOperationEntity", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("ArchiveType")
                        .HasColumnType("int");

                    b.Property<int>("OperationType")
                        .HasColumnType("int");

                    b.Property<int>("CurrentBatch")
                        .HasColumnType("int");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InitiatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InitiatedByName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("NumberOfBatches")
                        .HasColumnType("int");

                    b.Property<int>("NumberOfMessagesProcessed")
                        .HasColumnType("int");

                    b.Property<string>("OperationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Started")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalNumberOfMessages")
                        .HasColumnType("int");

                    b.HasKey("RequestId", "ArchiveType", "OperationType");

                    b.HasIndex("Started");

                    b.ToTable("ArchiveOperations");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.CustomCheckEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomCheckId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginatingEndpointHost")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OriginatingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OriginatingEndpointName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReportedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReportedAt");

                    b.HasIndex("Status", "ReportedAt");

                    b.ToTable("CustomChecks");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.EndpointSettingsEntity", b =>
                {
                    b.Property<string>("Name")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("TrackInstances")
                        .HasColumnType("bit");

                    b.HasKey("Name");

                    b.ToTable("EndpointSettings");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.EventLogItemEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("RaisedAt")
                        .HasColumnType("datetime2");

                    b.PrimitiveCollection<string>("RelatedTo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RaisedAt", "Id")
                        .IsDescending();

                    b.ToTable("EventLogItems", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedErrorImportEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Body")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("bit");

                    b.Property<string>("ExceptionInfo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FailedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UniqueMessageId");

                    b.HasIndex("FailedAt");

                    b.ToTable("FailedErrorImports");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BodyContentType")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<bool>("BodyStoredExternally")
                        .HasColumnType("bit");

                    b.Property<string>("BodyText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExceptionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FailingEndpointAddress")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("FirstTimeOfFailure")
                        .HasColumnType("datetime2");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<DateTime>("LastAttemptedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastTimeOfFailure")
                        .HasColumnType("datetime2");

                    b.Property<string>("MessageId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("MessageType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfProcessingAttempts")
                        .HasColumnType("int");

                    b.Property<string>("ReceivingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("ReceivingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SendingEndpointHost")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("SendingEndpointHostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SendingEndpointName")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("StatusChangedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("datetime2");

                    b.HasKey("UniqueMessageId");

                    b.HasIndex("ConversationId");

                    b.HasIndex("FailingEndpointAddress");

                    b.HasIndex("ReceivingEndpointName");

                    b.HasIndex("StatusChangedAt")
                        .HasFilter("[Status] IN (2, 4)");

                    b.HasIndex("TimeSent");

                    b.HasIndex("Status", "LastModified");

                    b.ToTable("FailedMessages");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.Property<Guid>("FailedMessageUniqueId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("FailedMessageUniqueId", "GroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("Type", "GroupId");

                    b.ToTable("FailedMessageGroups");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageRetryEntity", b =>
                {
                    b.Property<Guid>("UniqueMessageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RetryBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("StageAttempts")
                        .HasColumnType("int");

                    b.HasKey("UniqueMessageId");

                    b.HasIndex("RetryBatchId");

                    b.ToTable("FailedMessageRetries");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.GroupCommentEntity", b =>
                {
                    b.Property<string>("GroupId")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GroupId");

                    b.ToTable("GroupComments");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.HistoricRetryOperationEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Failed")
                        .HasColumnType("bit");

                    b.Property<int>("NumberOfMessagesProcessed")
                        .HasColumnType("int");

                    b.Property<string>("Originator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("RetryType")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompletionTime", "Id")
                        .IsDescending();

                    b.ToTable("HistoricRetryOperations");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Monitored")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.ToTable("KnownEndpoints");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.LicensingEndpointEntity", b =>
                {
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ThroughputSource")
                        .HasColumnType("int");

                    b.PrimitiveCollection<string>("EndpointIndicators")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("NormalizedSanitizedName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SanitizedName")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Scope")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserIndicator")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("NormalizedName", "ThroughputSource");

                    b.HasIndex("NormalizedSanitizedName");

                    b.ToTable("LicensingEndpoints");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.LicensingEndpointThroughputEntity", b =>
                {
                    b.Property<string>("NormalizedName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("ThroughputSource")
                        .HasColumnType("int");

                    b.Property<DateOnly>("DateUtc")
                        .HasColumnType("date");

                    b.Property<long>("MessageCount")
                        .HasColumnType("bigint");

                    b.HasKey("NormalizedName", "ThroughputSource", "DateUtc");

                    b.HasIndex("DateUtc");

                    b.ToTable("LicensingEndpointThroughput");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.MessageRedirectEntity", b =>
                {
                    b.Property<string>("FromPhysicalAddress")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ToPhysicalAddress")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FromPhysicalAddress");

                    b.ToTable("MessageRedirects");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.RetryBatchEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Classifier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Context")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InitialBatchSize")
                        .HasColumnType("int");

                    b.Property<string>("InitiatedById")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("InitiatedByName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("Last")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Originator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RetrySessionId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("RetryType")
                        .HasColumnType("int");

                    b.Property<string>("StagingId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Status", "RetrySessionId");

                    b.ToTable("RetryBatches");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.RetryBatchNowForwardingEntity", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<Guid>("RetryBatchId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("RetryBatchNowForwarding");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.SettingEntity", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.SubscriptionEntity", b =>
                {
                    b.Property<string>("MessageType")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TransportAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("MessageType", "TransportAddress");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.UnacknowledgedRetryOperationEntity", b =>
                {
                    b.Property<string>("RequestId")
                        .HasMaxLength(400)
                        .HasColumnType("nvarchar(400)");

                    b.Property<int>("RetryType")
                        .HasColumnType("int");

                    b.Property<string>("Classifier")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CompletionTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Failed")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Last")
                        .HasColumnType("datetime2");

                    b.Property<int>("NumberOfMessagesProcessed")
                        .HasColumnType("int");

                    b.Property<string>("Originator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.HasKey("RequestId", "RetryType");

                    b.ToTable("UnacknowledgedRetryOperations");
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.FailedMessageGroupEntity", b =>
                {
                    b.HasOne("ServiceControl.Persistence.EFCore.Entities.FailedMessageEntity", null)
                        .WithMany()
                        .HasForeignKey("FailedMessageUniqueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ServiceControl.Persistence.EFCore.Entities.LicensingEndpointThroughputEntity", b =>
                {
                    b.HasOne("ServiceControl.Persistence.EFCore.Entities.LicensingEndpointEntity", null)
                        .WithMany()
                        .HasForeignKey("NormalizedName", "ThroughputSource")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
