// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceControl.Audit.Persistence.Sql.SqlServer;

#nullable disable

namespace ServiceControl.Audit.Persistence.Sql.SqlServer.Migrations
{
    [DbContext(typeof(SqlServerAuditDbContext))]
    [Migration("20260123032858_AddFullTextIndexForSearch")]
    partial class AddFullTextIndexForSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.FailedAuditImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("FailedAuditImports", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.ProcessedMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Body")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BodyNotStored")
                        .HasColumnType("bit");

                    b.Property<int>("BodySize")
                        .HasColumnType("int");

                    b.Property<string>("BodyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<long?>("CriticalTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<long?>("DeliveryTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("bit");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MessageType")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<long?>("ProcessingTimeTicks")
                        .HasColumnType("bigint");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("datetime2");

                    b.Property<string>("UniqueMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("UniqueMessageId");

                    b.HasIndex("ConversationId", "ProcessedAt");

                    b.HasIndex("IsSystemMessage", "TimeSent", "ProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "IsSystemMessage", "ProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "IsSystemMessage", "TimeSent", "ProcessedAt");

                    b.ToTable("ProcessedMessages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.SagaSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("InitiatingMessageJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutgoingMessagesJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("StateAfterChange")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("SagaId");

                    b.ToTable("SagaSnapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
