using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace ServiceControl.Audit.Persistence.Sql.PostgreSQL.Migrations
{
    /// <inheritdoc />
    public partial class AddPartitioningAndFullTextSearch : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // PostgreSQL requires PARTITION BY RANGE at table creation time.
            // Drop and recreate ProcessedMessages and SagaSnapshots as partitioned tables.

            // Drop existing tables (no data to preserve — not in production)
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS processed_messages;
                """);

            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS saga_snapshots;
                """);

            // Recreate processed_messages as a partitioned table
            migrationBuilder.Sql("""
                CREATE TABLE processed_messages (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    processed_at timestamp with time zone NOT NULL,
                    unique_message_id character varying(200) NOT NULL,
                    headers_json text NOT NULL,
                    searchable_content text,
                    message_id character varying(200),
                    message_type character varying(500),
                    time_sent timestamp with time zone,
                    is_system_message boolean NOT NULL,
                    status integer NOT NULL,
                    conversation_id character varying(200),
                    receiving_endpoint_name character varying(500),
                    critical_time_ticks bigint,
                    processing_time_ticks bigint,
                    delivery_time_ticks bigint,
                    body_size integer NOT NULL,
                    body_url character varying(500),
                    body_not_stored boolean NOT NULL,
                    CONSTRAINT "PK_processed_messages" PRIMARY KEY (id, processed_at)
                ) PARTITION BY RANGE (processed_at);
                """);

            // Recreate indexes on processed_messages
            migrationBuilder.Sql("""
                CREATE INDEX "IX_processed_messages_unique_message_id_processed_at"
                ON processed_messages (unique_message_id, processed_at);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX "IX_processed_messages_message_id_processed_at"
                ON processed_messages (message_id, processed_at);
                """);

            migrationBuilder.Sql("""
                CREATE INDEX "IX_processed_messages_conversation_id_processed_at"
                ON processed_messages (conversation_id, processed_at);
                """);

            // Recreate saga_snapshots as a partitioned table
            migrationBuilder.Sql("""
                CREATE TABLE saga_snapshots (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    processed_at timestamp with time zone NOT NULL,
                    saga_id uuid NOT NULL,
                    saga_type text NOT NULL,
                    start_time timestamp with time zone NOT NULL,
                    finish_time timestamp with time zone NOT NULL,
                    status integer NOT NULL,
                    state_after_change text NOT NULL,
                    initiating_message_json text NOT NULL,
                    outgoing_messages_json text NOT NULL,
                    endpoint text NOT NULL,
                    CONSTRAINT "PK_saga_snapshots" PRIMARY KEY (id, processed_at)
                ) PARTITION BY RANGE (processed_at);
                """);

            // Recreate indexes on saga_snapshots
            migrationBuilder.Sql("""
                CREATE INDEX "IX_saga_snapshots_saga_id_processed_at"
                ON saga_snapshots (saga_id, processed_at);
                """);

            // Create GIN index for full-text search
            migrationBuilder.Sql("""
                CREATE INDEX ix_processed_messages_searchable_content
                ON processed_messages
                USING GIN (to_tsvector('simple', searchable_content));
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Drop partitioned tables and recreate as regular tables
            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS processed_messages;
                """);

            migrationBuilder.Sql("""
                DROP TABLE IF EXISTS saga_snapshots;
                """);

            // Recreate as non-partitioned tables
            migrationBuilder.Sql("""
                CREATE TABLE processed_messages (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    processed_at timestamp with time zone NOT NULL,
                    unique_message_id character varying(200) NOT NULL,
                    headers_json text NOT NULL,
                    searchable_content text,
                    message_id character varying(200),
                    message_type character varying(500),
                    time_sent timestamp with time zone,
                    is_system_message boolean NOT NULL,
                    status integer NOT NULL,
                    conversation_id character varying(200),
                    receiving_endpoint_name character varying(500),
                    critical_time_ticks bigint,
                    processing_time_ticks bigint,
                    delivery_time_ticks bigint,
                    body_size integer NOT NULL,
                    body_url character varying(500),
                    body_not_stored boolean NOT NULL,
                    CONSTRAINT "PK_processed_messages" PRIMARY KEY (id, processed_at)
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX "IX_processed_messages_unique_message_id_processed_at"
                ON processed_messages (unique_message_id, processed_at);
                CREATE INDEX "IX_processed_messages_message_id_processed_at"
                ON processed_messages (message_id, processed_at);
                CREATE INDEX "IX_processed_messages_conversation_id_processed_at"
                ON processed_messages (conversation_id, processed_at);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE saga_snapshots (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    processed_at timestamp with time zone NOT NULL,
                    saga_id uuid NOT NULL,
                    saga_type text NOT NULL,
                    start_time timestamp with time zone NOT NULL,
                    finish_time timestamp with time zone NOT NULL,
                    status integer NOT NULL,
                    state_after_change text NOT NULL,
                    initiating_message_json text NOT NULL,
                    outgoing_messages_json text NOT NULL,
                    endpoint text NOT NULL,
                    CONSTRAINT "PK_saga_snapshots" PRIMARY KEY (id, processed_at)
                );
                """);

            migrationBuilder.Sql("""
                CREATE INDEX "IX_saga_snapshots_saga_id_processed_at"
                ON saga_snapshots (saga_id, processed_at);
                """);
        }
    }
}
