using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ServiceControl.Audit.Persistence.Sql.PostgreSQL.Migrations
{
    /// <inheritdoc />
    public partial class InitialCreate : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "failed_audit_imports",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    message_json = table.Column<string>(type: "text", nullable: false),
                    exception_info = table.Column<string>(type: "text", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_failed_audit_imports", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "known_endpoints",
                columns: table => new
                {
                    id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    host_id = table.Column<Guid>(type: "uuid", nullable: false),
                    host = table.Column<string>(type: "text", nullable: false),
                    last_seen = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_known_endpoints", x => x.id);
                });

            migrationBuilder.CreateTable(
                name: "known_endpoints_insert_only",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    known_endpoint_id = table.Column<Guid>(type: "uuid", nullable: false),
                    name = table.Column<string>(type: "text", nullable: false),
                    host_id = table.Column<Guid>(type: "uuid", nullable: false),
                    host = table.Column<string>(type: "text", nullable: false),
                    last_seen = table.Column<DateTime>(type: "timestamp with time zone", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_known_endpoints_insert_only", x => x.id);
                });

            // Hand-crafted: EF Core doesn't support PARTITION BY RANGE, so we use raw SQL
            migrationBuilder.Sql("""
                CREATE TABLE processed_messages (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    created_on timestamp with time zone NOT NULL,
                    unique_message_id character varying(200) NOT NULL,
                    headers_json text NOT NULL,
                    searchable_content text,
                    message_id character varying(200),
                    message_type character varying(500),
                    time_sent timestamp with time zone,
                    is_system_message boolean NOT NULL,
                    status integer NOT NULL,
                    conversation_id character varying(200),
                    receiving_endpoint_name character varying(500),
                    critical_time_ticks bigint,
                    processing_time_ticks bigint,
                    delivery_time_ticks bigint,
                    body_size integer NOT NULL,
                    body_url character varying(500),
                    body_not_stored boolean NOT NULL,
                    CONSTRAINT "PK_processed_messages" PRIMARY KEY (id, created_on)
                ) PARTITION BY RANGE (created_on);
                """);

            migrationBuilder.Sql("""
                CREATE TABLE saga_snapshots (
                    id bigint GENERATED BY DEFAULT AS IDENTITY,
                    created_on timestamp with time zone NOT NULL,
                    saga_id uuid NOT NULL,
                    saga_type text NOT NULL,
                    start_time timestamp with time zone NOT NULL,
                    finish_time timestamp with time zone NOT NULL,
                    status integer NOT NULL,
                    state_after_change text NOT NULL,
                    initiating_message_json text NOT NULL,
                    outgoing_messages_json text NOT NULL,
                    endpoint text NOT NULL,
                    CONSTRAINT "PK_saga_snapshots" PRIMARY KEY (id, created_on)
                ) PARTITION BY RANGE (created_on);
                """);

            migrationBuilder.CreateIndex(
                name: "IX_known_endpoints_last_seen",
                table: "known_endpoints",
                column: "last_seen");

            migrationBuilder.CreateIndex(
                name: "IX_known_endpoints_insert_only_known_endpoint_id",
                table: "known_endpoints_insert_only",
                column: "known_endpoint_id");

            migrationBuilder.CreateIndex(
                name: "IX_known_endpoints_insert_only_last_seen",
                table: "known_endpoints_insert_only",
                column: "last_seen");

            migrationBuilder.CreateIndex(
                name: "IX_processed_messages_conversation_id_created_on",
                table: "processed_messages",
                columns: new[] { "conversation_id", "created_on" });

            migrationBuilder.CreateIndex(
                name: "IX_processed_messages_message_id_created_on",
                table: "processed_messages",
                columns: new[] { "message_id", "created_on" });

            migrationBuilder.CreateIndex(
                name: "IX_processed_messages_time_sent",
                table: "processed_messages",
                column: "time_sent");

            migrationBuilder.CreateIndex(
                name: "IX_processed_messages_unique_message_id_created_on",
                table: "processed_messages",
                columns: new[] { "unique_message_id", "created_on" });

            migrationBuilder.CreateIndex(
                name: "IX_saga_snapshots_saga_id_created_on",
                table: "saga_snapshots",
                columns: new[] { "saga_id", "created_on" });

            // Hand-crafted: Full-text search GIN index
            migrationBuilder.Sql("""
                CREATE INDEX ix_processed_messages_searchable_content
                ON processed_messages
                USING GIN (to_tsvector('simple', searchable_content));
                """);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "failed_audit_imports");

            migrationBuilder.DropTable(
                name: "known_endpoints");

            migrationBuilder.DropTable(
                name: "known_endpoints_insert_only");

            migrationBuilder.DropTable(
                name: "processed_messages");

            migrationBuilder.DropTable(
                name: "saga_snapshots");
        }
    }
}
