// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServiceControl.Audit.Persistence.Sql.PostgreSQL;

#nullable disable

namespace ServiceControl.Audit.Persistence.Sql.PostgreSQL.Migrations
{
    [DbContext(typeof(PostgreSqlAuditDbContext))]
    partial class PostgreSqlAuditDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.FailedAuditImportEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ExceptionInfo")
                        .HasColumnType("text")
                        .HasColumnName("exception_info");

                    b.Property<string>("MessageJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("message_json");

                    b.HasKey("Id");

                    b.ToTable("failed_audit_imports", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.KnownEndpointEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("LastSeen");

                    b.ToTable("known_endpoints", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.KnownEndpointInsertOnlyEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Host")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("host");

                    b.Property<Guid>("HostId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_id");

                    b.Property<Guid>("KnownEndpointId")
                        .HasColumnType("uuid")
                        .HasColumnName("known_endpoint_id");

                    b.Property<DateTime>("LastSeen")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("KnownEndpointId");

                    b.HasIndex("LastSeen");

                    b.ToTable("known_endpoints_insert_only", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.ProcessedMessageEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<bool>("BodyNotStored")
                        .HasColumnType("boolean")
                        .HasColumnName("body_not_stored");

                    b.Property<int>("BodySize")
                        .HasColumnType("integer")
                        .HasColumnName("body_size");

                    b.Property<string>("BodyUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("body_url");

                    b.Property<string>("ConversationId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("conversation_id");

                    b.Property<long?>("CriticalTimeTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("critical_time_ticks");

                    b.Property<long?>("DeliveryTimeTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("delivery_time_ticks");

                    b.Property<string>("HeadersJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("headers_json");

                    b.Property<bool>("IsSystemMessage")
                        .HasColumnType("boolean")
                        .HasColumnName("is_system_message");

                    b.Property<string>("MessageId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("message_id");

                    b.Property<string>("MessageType")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message_type");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<long?>("ProcessingTimeTicks")
                        .HasColumnType("bigint")
                        .HasColumnName("processing_time_ticks");

                    b.Property<string>("ReceivingEndpointName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("receiving_endpoint_name");

                    b.Property<string>("SearchableContent")
                        .HasColumnType("text")
                        .HasColumnName("searchable_content");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("TimeSent")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time_sent");

                    b.Property<string>("UniqueMessageId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("unique_message_id");

                    b.HasKey("Id");

                    b.HasIndex("MessageId");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("UniqueMessageId");

                    b.HasIndex("ConversationId", "ProcessedAt");

                    b.HasIndex("IsSystemMessage", "TimeSent", "ProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "IsSystemMessage", "ProcessedAt");

                    b.HasIndex("ReceivingEndpointName", "IsSystemMessage", "TimeSent", "ProcessedAt")
                        .HasDatabaseName("IX_processed_messages_receiving_endpoint_name_is_system_messa~1");

                    b.ToTable("processed_messages", (string)null);
                });

            modelBuilder.Entity("ServiceControl.Audit.Persistence.Sql.Core.Entities.SagaSnapshotEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Endpoint")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("endpoint");

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("finish_time");

                    b.Property<string>("InitiatingMessageJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("initiating_message_json");

                    b.Property<string>("OutgoingMessagesJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("outgoing_messages_json");

                    b.Property<DateTime>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<Guid>("SagaId")
                        .HasColumnType("uuid")
                        .HasColumnName("saga_id");

                    b.Property<string>("SagaType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("saga_type");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("StateAfterChange")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("state_after_change");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ProcessedAt");

                    b.HasIndex("SagaId");

                    b.ToTable("saga_snapshots", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
