<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <TestCategory>Raven</TestCategory>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="ServiceControl.AcceptanceTests.RavenDB" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ServiceControl.AcceptanceTesting\ServiceControl.AcceptanceTesting.csproj" />
    <ProjectReference Include="..\ServiceControl.Persistence.RavenDB\ServiceControl.Persistence.RavenDB.csproj" />
    <ProjectReference Include="..\ServiceControl.Transports.Learning\ServiceControl.Transports.Learning.csproj" />
    <ProjectReference Include="..\ServiceControl\ServiceControl.csproj" />
    <ProjectReference Include="..\TestHelper\TestHelper.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GitHubActionsTestLogger" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="NServiceBus.Heartbeat" />
    <PackageReference Include="NServiceBus.SagaAudit" />
    <PackageReference Include="NUnit" />
    <PackageReference Include="NUnit.Analyzers" />
    <PackageReference Include="NUnit3TestAdapter" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\ServiceControl.AcceptanceTests\**\*.cs" LinkBase="Shared" />
    <Compile Include="..\ServiceControl.Persistence.Tests.RavenDB\SharedEmbeddedServer.cs" />
    <Compile Include="..\ServiceControl.Persistence.Tests.RavenDB\StopSharedDatabase.cs" />
    <Compile Include="..\ServiceControl.UnitTests\NUnitParallelRunnerSettings.cs" />

    <!-- Error ingestion only mode is supported on SQL Server and PostgreSQL storage only. -->
    <Compile Remove="..\ServiceControl.AcceptanceTests\Recoverability\When_hosting_error_ingestion_only.cs" />
    <Compile Remove="..\ServiceControl.AcceptanceTests\Auditing\When_composing_audit_ingestion_in_the_primary.cs" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Shared\Recoverability\ExternalIntegration\" />
  </ItemGroup>

</Project>
