# Selects the test projects belonging to a test category, so that CI can build and run only those
# rather than the whole solution. The category is declared by the <TestCategory> property in each test
# project, which must match the Filter of the assembly-level IncludeIn*Tests attribute in that project.
#
# Writes the selected project paths to $GITHUB_OUTPUT as 'test-projects', and generates an MSBuild
# traversal project so that `dotnet build` can build the whole selection in one graph.
#
# Use -List to print every category and its projects without writing any files.

[CmdletBinding(DefaultParameterSetName = 'Select')]
param(
    [Parameter(Mandatory, ParameterSetName = 'Select')]
    [string]$Category,

    [Parameter(ParameterSetName = 'Select')]
    [string]$TraversalProjectPath = 'tests.proj',

    [Parameter(Mandatory, ParameterSetName = 'List')]
    [switch]$List
)

$ErrorActionPreference = 'Stop'

$projectsByCategory = @{}

# -Filter rather than -Include: the provider applies it during traversal, which is dramatically faster
# on a tree that already contains bin/obj output.
Get-ChildItem -Path src -Filter '*.csproj' -Recurse -File | ForEach-Object {
    $testCategory = (Select-Xml -Path $_.FullName -XPath "/Project/PropertyGroup/TestCategory").Node.InnerText

    if ([string]::IsNullOrWhiteSpace($testCategory)) {
        return
    }

    if (-not $projectsByCategory.ContainsKey($testCategory)) {
        $projectsByCategory[$testCategory] = New-Object Collections.Generic.List[String]
    }

    $projectsByCategory[$testCategory].Add((Resolve-Path -Relative $_.FullName))
}

if ($List) {
    foreach ($key in $projectsByCategory.Keys | Sort-Object) {
        Write-Output "$key"
        $projectsByCategory[$key] | Sort-Object | ForEach-Object { Write-Output "  $_" }
    }
    return
}

if (-not $projectsByCategory.ContainsKey($Category)) {
    $known = ($projectsByCategory.Keys | Sort-Object) -join ', '
    throw "No test project declares <TestCategory>$Category</TestCategory>. Known categories: $known"
}

$projects = $projectsByCategory[$Category] | Sort-Object

Write-Output "Test category '$Category' selects $($projects.Count) project(s):"
$projects | ForEach-Object { Write-Output "  $_" }

# ReferenceOutputAssembly is irrelevant here because the traversal project produces nothing itself.
# TargetFramework is undefined per reference so that projects targeting net10.0-windows are not forced
# onto the traversal project's own framework, matching the convention in ProjectReferences.Transports.props.
$references = $projects | ForEach-Object {
    "    <ProjectReference Include=`"$($_ -replace '\\', '/')`" SkipGetTargetFrameworkProperties=`"true`" UndefineProperties=`"TargetFramework`" />"
}

$traversal = @"
<!-- Generated by tools/select-test-projects.ps1 for test category '$Category'. Do not commit. -->
<Project Sdk="Microsoft.Build.NoTargets/3.7.134">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
$($references -join [Environment]::NewLine)
  </ItemGroup>

</Project>
"@

Set-Content -Path $TraversalProjectPath -Value $traversal -Encoding utf8
Write-Output "Wrote traversal project to $TraversalProjectPath"

if ($Env:GITHUB_OUTPUT) {
    "test-projects<<PROJECTS_EOF" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
    $projects | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
    "PROJECTS_EOF" | Out-File -FilePath $Env:GITHUB_OUTPUT -Encoding utf8 -Append
}
