FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /servicecontrol

ADD /ServiceControl.Transports.SQS/bin/Release/net462 .
ADD /ServiceControl/bin/Release/net462 .

ENV "ServiceControl/TransportType"="ServiceControl.Transports.SQS.SQSTransportCustomization, ServiceControl.Transports.SQS"
ENV "ServiceControl/Hostname"="*"

ENV "ServiceControl/DBPath"="C:\\Data\\"
ENV "ServiceControl/LogPath"="C:\\Logs\\"

EXPOSE 33333
EXPOSE 33334

ENTRYPOINT ["./ServiceControl.exe", "--portable"]