FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /servicecontrol

ADD /ServiceControl.Transports.ASQ/bin/Release/net461 .
ADD /ServiceControl/bin/Release/net461 .

ENV "ServiceControl/TransportType"="ServiceControl.Transports.ASQ.ASQTransportCustomization, ServiceControl.Transports.ASQ"
ENV "ServiceControl/Hostname"="*"

ENV "ServiceControl/DBPath"="C:\\Data\\"
ENV "ServiceControl/LogPath"="C:\\Logs\\"

EXPOSE 33333
EXPOSE 33334

ENTRYPOINT ["./ServiceControl.exe", "--portable"]