FROM mcr.microsoft.com/windows/servercore:ltsc2019

WORKDIR /servicecontrol

ADD /ServiceControl.Transports.ASB/bin/Release/net461 .
ADD /ServiceControl/bin/Release/net461 .

ENV "ServiceControl/TransportType"="ServiceControl.Transports.ASB.ASBForwardingTopologyTransportCustomization, ServiceControl.Transports.ASB"
ENV "ServiceControl/Hostname"="*"

ENV "ServiceControl/DBPath"="C:\\Data\\"
ENV "ServiceControl/LogPath"="C:\\Logs\\"

ENTRYPOINT ["./ServiceControl.exe", "--portable", "--setup"]