namespace ServiceControl.Audit.AcceptanceTests.Recoverability
{
    using System;
    using System.Threading.Tasks;
    using AcceptanceTesting.EndpointTemplates;
    using Microsoft.Extensions.DependencyInjection;
    using NServiceBus;
    using NServiceBus.AcceptanceTesting;
    using NServiceBus.Features;
    using NServiceBus.Pipeline;
    using NUnit.Framework;
    using Conventions = NServiceBus.AcceptanceTesting.Customization.Conventions;


    class When_a_successful_retry_at_old_endpoint_is_detected : AcceptanceTest
    {
        [Test]
        public async Task Should_send_acknowledgement()
        {
            var failedMessageId = Guid.NewGuid().ToString();
            var context = await Define<Context>()
                .WithEndpoint<AckSpy>()
                .WithEndpoint<Receiver>(b => b.When(s =>
                {
                    var options = new SendOptions();

                    options.SetHeader("ServiceControl.Retry.UniqueMessageId", failedMessageId);
                    options.SetHeader("ServiceControl.Retry.AcknowledgementQueue", Conventions.EndpointNamingConvention(typeof(AckSpy)));
                    options.RouteToThisEndpoint();
                    return s.Send(new MyMessage(), options);
                }))
                .Done(c => c.AcknowledgementSent)
                .Run();

            Assert.That(context.AcknowledgementSent, Is.True);
        }

        public class Context : ScenarioContext
        {
            public bool AcknowledgementSent { get; set; }
        }

        public class AckSpy : EndpointConfigurationBuilder
        {
            public AckSpy() =>
                EndpointSetup<DefaultServerWithoutAudit>(cfg =>
                {
                    cfg.Pipeline.Register(b => new SpyBehavior(b.GetRequiredService<Context>()), "Spy behavior");
                    cfg.Pipeline.Replace("DiscardMessagesBehavior", typeof(EmptyBehavior)); //Otherwise the confirmation generated by the audit instance will be discarded
                });

            public class SpyBehavior(Context testContext) : Behavior<ITransportReceiveContext>
            {
                public override Task Invoke(ITransportReceiveContext context, Func<Task> next)
                {
                    if (context.Message.Headers.ContainsKey("ServiceControl.Retry.Successful"))
                    {
                        testContext.AcknowledgementSent = true;
                    }
                    return Task.CompletedTask;
                }
            }

            public class EmptyBehavior : Behavior<ITransportReceiveContext>
            {
                public override Task Invoke(ITransportReceiveContext context, Func<Task> next) => next();
            }
        }

        public class Receiver : EndpointConfigurationBuilder
        {
            public Receiver() =>
                EndpointSetup<DefaultServerWithAudit>(cfg =>
                {
                    // disable retry notifications feature to emulate an NServiceBus endpoint older than version 7.5
                    cfg.DisableFeature<PlatformRetryNotifications>();
                });

            public class MyMessageHandler : IHandleMessages<MyMessage>
            {
                public Task Handle(MyMessage message, IMessageHandlerContext context) => Task.CompletedTask;
            }
        }

        public class MyMessage : ICommand;
    }
}