on:
  workflow_call:
jobs:
  containers:
    runs-on: ubuntu-22.04
    name: ${{ matrix.name }}
    defaults:
      run:
        shell: bash
    strategy:
      matrix:
        include:
          - name: servicecontrol
            project: ServiceControl
          - name: servicecontrol-audit
            project: ServiceControl.Audit
          - name: servicecontrol-monitoring
            project: ServiceControl.Monitoring
      fail-fast: false
    steps:
      - name: Check for secrets
        env:
          SECRETS_AVAILABLE: ${{ secrets.SECRETS_AVAILABLE }}
        shell: pwsh
        run: exit $(If ($env:SECRETS_AVAILABLE -eq 'true') { 0 } Else { 1 })
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0
      - name: Run MinVer
        uses: Particular/run-minver-action@v1.0.0
      - name: Validate build version
        if: ${{ github.event_name == 'push' && github.ref_type == 'tag' }}
        uses: ./.github/actions/validate-version
        with:
          version: ${{ env.MinVerVersion }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.9.0
      - name: Log in to GitHub container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Get current date
        id: date
        run: echo "date=$(date '+%FT%TZ')" >> $GITHUB_OUTPUT
      - name: Build and push image to GitHub container registry
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          sbom: true
          build-args: |
            VERSION=${{ env.MinVerVersion }}
            SHA=${{ github.sha }}
            CREATED=${{ steps.date.outputs.date }}
          file: src/${{ matrix.project }}/Dockerfile
          tags: ghcr.io/particular/${{ matrix.name }}:${{ github.event_name == 'pull_request' && format('pr-{0}', github.event.number) || env.MinVerVersion }}
